// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkG4PHKb114JejEBPYfhRY7IFIrPsyT_k',
    appId: '1:101481774756:web:c9c68a33918fb4e4633031',
    messagingSenderId: '101481774756',
    projectId: 'news-app-2bcff',
    authDomain: 'news-app-2bcff.firebaseapp.com',
    storageBucket: 'news-app-2bcff.appspot.com',
    measurementId: 'G-9361PBMMGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ_4jUplKRvUTxqSClkV4O4s1VSrLMIak',
    appId: '1:101481774756:android:88c478175c6bc8c8633031',
    messagingSenderId: '101481774756',
    projectId: 'news-app-2bcff',
    storageBucket: 'news-app-2bcff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS5LzpgViyRc-8QlaXlG4ushwq-gRTr6M',
    appId: '1:101481774756:ios:310525e192e8c7bb633031',
    messagingSenderId: '101481774756',
    projectId: 'news-app-2bcff',
    storageBucket: 'news-app-2bcff.appspot.com',
    iosClientId:
        '101481774756-gv0fims9jo1q9bc4lg7d2b9i9btbfm9q.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsAppFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS5LzpgViyRc-8QlaXlG4ushwq-gRTr6M',
    appId: '1:101481774756:ios:005c8f372d0a3e15633031',
    messagingSenderId: '101481774756',
    projectId: 'news-app-2bcff',
    storageBucket: 'news-app-2bcff.appspot.com',
    iosClientId:
        '101481774756-t37eneama48mj5e20mjb8lnchh8joccd.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsAppFinal.RunnerTests',
  );
}
